# -*- conf -*-
# qt6ct — Arc Dark + Papirus Under Qt Apps On Wayland

[Appearance]
style=Fusion
color_scheme=ArcDark.conf
icon_theme=Papirus-Dark
standard_dialogs=default
toolbutton_style=icon
font="Adwaita Sans,11,-1,5,50,0,0,0,0,0"
menu_font="Adwaita Sans,11,-1,5,50,0,0,0,0,0"
custom_palette=false

[Interface]
cursor_theme=default
double_click_interval=400
cursor_blink_time=1200
show_shortcuts_in_context_menus=true
dialog_buttons_have_icons=false

[Fonts]
fixed="CaskaydiaCove Nerd Font,11,-1,5,50,0,0,0,0,0"