# -*- Vim -*-
" Vim Defaults — Modern Baseline Without Plugins
set nocompatible
set encoding=utf-8
filetype plugin indent on
syntax on

set number
set relativenumber
set cursorline
set mouse=a
set clipboard^=unnamed,unnamedplus
set backspace=indent,eol,start
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smartindent
set autoindent
set ignorecase
set smartcase
set incsearch
set hlsearch
set showmatch
set wildmenu
set wildmode=list:longest,full
set laststatus=2
set showcmd
set showtabline=2
set scrolloff=5
set sidescrolloff=5
set updatetime=300
set timeout timeoutlen=500 ttimeoutlen=50
set ttyfast
set undofile
set undodir=~/.local/state/vim/undo//
set backupdir=~/.local/state/vim/backup//
set directory=~/.local/state/vim/swap//
set viminfo+=n~/.local/state/vim/viminfo
set signcolumn=yes
set splitbelow
set splitright
set termguicolors
set background=dark
set completeopt=menuone,noselect
set nofoldenable
set conceallevel=0

" Netrw
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25

" Arc Dark-ish Colors
function! s:ArcDarkHighlights() abort
    hi clear
    if exists('g:syntax_on')
        syntax reset
    endif
    set background=dark
    hi Normal       guifg=#d3dae3 guibg=#2f343f
    hi Comment      guifg=#7f8794 gui=italic
    hi Constant     guifg=#f3d469
    hi String       guifg=#96d988
    hi Identifier   guifg=#86a2be
    hi Function     guifg=#5294e2
    hi Statement    guifg=#d0afca
    hi Keyword      guifg=#d0afca
    hi PreProc      guifg=#8bc7c6
    hi Type         guifg=#f8606a
    hi Special      guifg=#f8606a
    hi Visual       guibg=#4a4e59
    hi CursorLine   guibg=#3b4152
    hi LineNr       guifg=#5c616c guibg=NONE
    hi CursorLineNr guifg=#d3dae3 guibg=#3b4152
    hi StatusLine   guifg=#ffffff guibg=#3b4152
    hi StatusLineNC guifg=#8b8f98 guibg=#33363d
    hi Pmenu        guifg=#d3dae3 guibg=#3b4152
    hi PmenuSel     guifg=#ffffff guibg=#5294e2
    hi MatchParen   guifg=#f8606a guibg=#3b4152
    hi Search       guifg=#ffffff guibg=#5294e2
    hi IncSearch    guifg=#ffffff guibg=#f8606a
    hi Error        guifg=#f8606a guibg=NONE
    hi Todo         guifg=#f3d469 guibg=NONE gui=bold
endfunction

augroup custom_colors
    autocmd!
    autocmd ColorScheme * call s:ArcDarkHighlights()
    autocmd VimEnter,BufWinEnter * call s:ArcDarkHighlights()
augroup END

" Leader Basics
let mapleader = ' '
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>e :Lexplore<CR>
nnoremap <C-s> :w<CR>
vnoremap <C-s> <Esc>:w<CR>
inoremap <C-s> <Esc>:w<CR>
nnoremap <C-n> :nohlsearch<CR>

" Sensible Splits Navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-j>
nnoremap <C-k> <C-k>
nnoremap <C-l> <C-l>