# -*- Conf -*-
# GTK Settings Applied System-Wide For The User (Also Mirrors Gsettings)

[Settings]
gtk-theme-name = Arc-Dark
gtk-icon-theme-name = Papirus-Dark
gtk-font-name = Adwaita Sans 11
gtk-cursor-theme-name = default
gtk-cursor-theme-size = 24
gtk-toolbar-style = GTK_TOOLBAR_ICONS
gtk-menu-icons = true
gtk-button-images = true
gtk-application-prefer-dark-theme = true
gtk-xft-antialias = 1
gtk-xft-hinting = 1
gtk-xft-hintstyle = hintslight
gtk-xft-rgba = rgb
gtk-monospace-font-name = CaskaydiaCove Nerd Font 11
gtk-enable-animations = true