# -*- conf -*-
# GTK4 Settings

[Settings]
gtk-theme-name = Arc-Dark
gtk-icon-theme-name = Papirus-Dark
gtk-font-name = Adwaita Sans 11
gtk-application-prefer-dark-theme = true
gtk-cursor-theme-name = default
gtk-cursor-theme-size = 24
gtk-monospace-font-name = CaskaydiaCove Nerd Font 11