# -*- Conf -*-
# Autostart (Sourced From hyprland.conf)
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = hypridle
exec-once = quickshell -c shell
exec-once = nm-applet --indicator
exec-once = pasystray
exec-once = blueman-applet
exec-once = xfce4-power-manager
exec-once = nwg-clipman
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hyprpaper