# -*- Conf -*-
# Autostart (Sourced From hyprland.conf)
exec-once = hypridle
exec-once = quickshell -c shell
exec-once = nm-applet --indicator
exec-once = pasystray
exec-once = blueman-applet
exec-once = cbatticon
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hyprpaper